# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twitter.consumer.key: '%env(string:CONSUMER_KEY)%'
    twitter.consumer.secret: '%env(string:CONSUMER_SECRET)%'
    twitter.access.token: '%env(string:ACCESS_TOKEN)%'
    twitter.token.secret: '%env(string:ACCESS_TOKEN_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    twitter_oauth_client:
        class: Abraham\TwitterOAuth\TwitterOAuth
        arguments:
            - '%twitter.consumer.key%'
            - '%twitter.consumer.secret%'
            - '%twitter.access.token%'
            - '%twitter.token.secret%'                                    
    
    App\Infrastructure\TwitterClient:
        arguments: ['@twitter_oauth_client']

    App\Application\Fetch:
        arguments: [App\Infrastructure\TwitterClient]